### ISSUE TITLE
The summoner is immuned to Wither during his summoning

### ISSUE THREAD

**Issue by mser7** [Daveyx0/TheSummoner#1]
When the overlay appear around him, he is immuned to Wither

**Comment by Daveyx0** [comment]
Is this a big issue? I mean for him to be invinsible during that state and dont see why wither should be excluded.

**Comment by mser7** [comment]
For what purpose? Evokers doesnt become invnerable during their magic attack

**Comment by Daveyx0** [comment]
The evoker tries to keep you away with its magic while a summoner only has its summons to defend. Its really easy to avoid the summons and kill the summoner right when you encounter one. I made him invulnerable for a few seconds so the player at least could not ignore the summons and go for the summoner immediately.
