### ISSUE TITLE
Chat Spam on Server

### ISSUE THREAD

**Issue by Xhale1** [Daveyx0/TheSummoner#4]
When running this on a dedicated server, I get constant bursts of chat spam, such as what is in the screenshot. I get the eight "summoner's entity dies" firing at once, then a short pause, then all the suffocating messages at once, pause, then dying again.

Let me know if you need any more info.

MultiMob 1.0.4 and The Summoner 1.0.1 are being used.

<img width="1025" alt="screen shot 2019-01-21 at 4 30 57 am" src="https://user-images.githubusercontent.com/6383154/51475278-c1e59980-1d36-11e9-9795-f03d40094c71.png">

**Comment by Xhale1** [comment]
As a sidenote, we are also using the Epic Siege Mod, which could be causing conflicts. Regardless, not a huge fan of the spam ;)

**Comment by Daveyx0** [comment]
Yeh this needs a fix asap. Looking into it

**Comment by Daveyx0** [comment]
This must be part of the vanilla follow code or something.... I will look into ways to disable it.

**Comment by Xhale1** [comment]
I believe I found the cause of this issue. Installing COFH will result in the death of named entities being displayed in the chat. This can be disabled in the configs for COFH. I should have figured this out earlier, my bad.

Although this might point to a different issue in which the summoner in that world was constantly summoning mobs that immediately died in walls. Not sure if that's an issue that needs to be looked into though.
