### ISSUE TITLE
Interaction with ZombieAwareness

### ISSUE THREAD

**Issue by lorientalxd** [Daveyx0/TheSummoner#8]
With ZombieAwareness installed the mobs affected by it will still attack you after being summoned. If you dont know the mod, it makes zombies(and any other mob you add to the config) aggro you from a greater distance, detecting the sound that you make and blood that you drop when you are hurt.

**Comment by Twichlove** [comment]
This is the same when a wither skeleton is set to sit, it will still attack you unless you have mods such as metamorph that makes hostile morphs neutral.

**Comment by lorientalxd** [comment]
I learned you can actually change this in the moblist configs of ZombieAwareness so it is not an issue
